[2024-07-24T14:14:38.380+0900] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T14:14:38.387+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_bash.copy.log scheduled__2024-07-23T00:00:00+00:00 [queued]>
[2024-07-24T14:14:38.390+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_bash.copy.log scheduled__2024-07-23T00:00:00+00:00 [queued]>
[2024-07-24T14:14:38.390+0900] {taskinstance.py:2306} INFO - Starting attempt 3 of 4
[2024-07-24T14:14:38.394+0900] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): copy.log> on 2024-07-23 00:00:00+00:00
[2024-07-24T14:14:38.396+0900] {standard_task_runner.py:64} INFO - Started process 90019 to run task
[2024-07-24T14:14:38.399+0900] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'simple_bash', 'copy.log', 'scheduled__2024-07-23T00:00:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/simple_bash.py', '--cfg-path', '/var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T/tmpvokkps81']
[2024-07-24T14:14:38.400+0900] {standard_task_runner.py:91} INFO - Job 83: Subtask copy.log
[2024-07-24T14:14:38.415+0900] {task_command.py:426} INFO - Running <TaskInstance: simple_bash.copy.log scheduled__2024-07-23T00:00:00+00:00 [running]> on host jeongui-MacBookPro.local
[2024-07-24T14:14:38.435+0900] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='simple_bash' AIRFLOW_CTX_TASK_ID='copy.log' AIRFLOW_CTX_EXECUTION_DATE='2024-07-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-23T00:00:00+00:00'
[2024-07-24T14:14:38.436+0900] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T14:14:38.442+0900] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T
[2024-07-24T14:14:38.442+0900] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            mkdir -p ~/data/20240723\n            cp ~/logs/history_20240723*.log ~/data/20240723/\n        ']
[2024-07-24T14:14:38.445+0900] {subprocess.py:86} INFO - Output:
[2024-07-24T14:14:38.449+0900] {subprocess.py:93} INFO - cp: /Users/DE32/logs/history_20240723*.log: No such file or directory
[2024-07-24T14:14:38.449+0900] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-24T14:14:38.449+0900] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T14:14:38.452+0900] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-24T14:14:38.454+0900] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=simple_bash, task_id=copy.log, run_id=scheduled__2024-07-23T00:00:00+00:00, execution_date=20240723T000000, start_date=20240724T051438, end_date=20240724T051438
[2024-07-24T14:14:38.458+0900] {standard_task_runner.py:110} ERROR - Failed to execute job 83 for task copy.log (Bash command failed. The command returned a non-zero exit code 1.; 90019)
[2024-07-24T14:14:38.504+0900] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-24T14:14:38.513+0900] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T14:14:38.513+0900] {local_task_job_runner.py:222} INFO - ::endgroup::
