[2024-07-24T16:11:50.325+0900] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T16:11:50.332+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: make_parquet.Check scheduled__2024-07-23T04:10:00+00:00 [queued]>
[2024-07-24T16:11:50.334+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: make_parquet.Check scheduled__2024-07-23T04:10:00+00:00 [queued]>
[2024-07-24T16:11:50.334+0900] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-24T16:11:50.338+0900] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): Check> on 2024-07-23 04:10:00+00:00
[2024-07-24T16:11:50.340+0900] {standard_task_runner.py:64} INFO - Started process 98279 to run task
[2024-07-24T16:11:50.343+0900] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'make_parquet', 'Check', 'scheduled__2024-07-23T04:10:00+00:00', '--job-id', '399', '--raw', '--subdir', 'DAGS_FOLDER/make_parquet.py', '--cfg-path', '/var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T/tmp8txdweax']
[2024-07-24T16:11:50.344+0900] {standard_task_runner.py:91} INFO - Job 399: Subtask Check
[2024-07-24T16:11:50.357+0900] {task_command.py:426} INFO - Running <TaskInstance: make_parquet.Check scheduled__2024-07-23T04:10:00+00:00 [running]> on host jeongui-MacBookPro.local
[2024-07-24T16:11:50.380+0900] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='make_parquet' AIRFLOW_CTX_TASK_ID='Check' AIRFLOW_CTX_EXECUTION_DATE='2024-07-23T04:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-23T04:10:00+00:00'
[2024-07-24T16:11:50.380+0900] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T16:11:50.386+0900] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T
[2024-07-24T16:11:50.386+0900] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'bash /Users/DE32/airflow/sh/simple_done_check.sh ~/data/done/_import/20240723/_DONE']
[2024-07-24T16:11:50.389+0900] {subprocess.py:86} INFO - Output:
[2024-07-24T16:11:50.393+0900] {subprocess.py:93} INFO - _DONE Path = /Users/DE32/data/done/_import/20240723/_DONE
[2024-07-24T16:11:50.393+0900] {subprocess.py:93} INFO - I'll be back =>
[2024-07-24T16:11:50.393+0900] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-24T16:11:50.394+0900] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T16:11:50.397+0900] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-24T16:11:50.399+0900] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=make_parquet, task_id=Check, run_id=scheduled__2024-07-23T04:10:00+00:00, execution_date=20240723T041000, start_date=20240724T071150, end_date=20240724T071150
[2024-07-24T16:11:50.402+0900] {standard_task_runner.py:110} ERROR - Failed to execute job 399 for task Check (Bash command failed. The command returned a non-zero exit code 1.; 98279)
[2024-07-24T16:11:50.450+0900] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-24T16:11:50.457+0900] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T16:11:50.458+0900] {local_task_job_runner.py:222} INFO - ::endgroup::
