[2024-07-24T15:06:13.650+0900] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T15:06:13.659+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_db.Check scheduled__2024-07-21T00:00:00+00:00 [queued]>
[2024-07-24T15:06:13.661+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_db.Check scheduled__2024-07-21T00:00:00+00:00 [queued]>
[2024-07-24T15:06:13.661+0900] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-24T15:06:13.665+0900] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): Check> on 2024-07-21 00:00:00+00:00
[2024-07-24T15:06:13.668+0900] {standard_task_runner.py:64} INFO - Started process 94355 to run task
[2024-07-24T15:06:13.670+0900] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'import_db', 'Check', 'scheduled__2024-07-21T00:00:00+00:00', '--job-id', '242', '--raw', '--subdir', 'DAGS_FOLDER/import_db.py', '--cfg-path', '/var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T/tmp4qnczflt']
[2024-07-24T15:06:13.672+0900] {standard_task_runner.py:91} INFO - Job 242: Subtask Check
[2024-07-24T15:06:13.686+0900] {task_command.py:426} INFO - Running <TaskInstance: import_db.Check scheduled__2024-07-21T00:00:00+00:00 [running]> on host jeongui-MacBookPro.local
[2024-07-24T15:06:13.709+0900] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='import_db' AIRFLOW_CTX_TASK_ID='Check' AIRFLOW_CTX_EXECUTION_DATE='2024-07-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-21T00:00:00+00:00'
[2024-07-24T15:06:13.709+0900] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T15:06:13.715+0900] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T
[2024-07-24T15:06:13.715+0900] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'bash /Users/DE32/airflow/sh/simple_done_check.sh ~/data/done/20240721/_DONE']
[2024-07-24T15:06:13.718+0900] {subprocess.py:86} INFO - Output:
[2024-07-24T15:06:13.721+0900] {subprocess.py:93} INFO - _DONE Path = /Users/DE32/data/done/20240721/_DONE
[2024-07-24T15:06:13.721+0900] {subprocess.py:93} INFO - I'll be back =>
[2024-07-24T15:06:13.721+0900] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-24T15:06:13.722+0900] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T15:06:13.725+0900] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-24T15:06:13.726+0900] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=import_db, task_id=Check, run_id=scheduled__2024-07-21T00:00:00+00:00, execution_date=20240721T000000, start_date=20240724T060613, end_date=20240724T060613
[2024-07-24T15:06:13.730+0900] {standard_task_runner.py:110} ERROR - Failed to execute job 242 for task Check (Bash command failed. The command returned a non-zero exit code 1.; 94355)
[2024-07-24T15:06:13.772+0900] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-24T15:06:13.778+0900] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T15:06:13.778+0900] {local_task_job_runner.py:222} INFO - ::endgroup::
