[2024-07-24T15:02:13.737+0900] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T15:02:13.744+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_db.err_report scheduled__2024-07-23T00:00:00+00:00 [queued]>
[2024-07-24T15:02:13.747+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_db.err_report scheduled__2024-07-23T00:00:00+00:00 [queued]>
[2024-07-24T15:02:13.747+0900] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-24T15:02:13.751+0900] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): err_report> on 2024-07-23 00:00:00+00:00
[2024-07-24T15:02:13.753+0900] {standard_task_runner.py:64} INFO - Started process 94235 to run task
[2024-07-24T15:02:13.756+0900] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'import_db', 'err_report', 'scheduled__2024-07-23T00:00:00+00:00', '--job-id', '232', '--raw', '--subdir', 'DAGS_FOLDER/import_db.py', '--cfg-path', '/var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T/tmp3mz3jnk2']
[2024-07-24T15:02:13.757+0900] {standard_task_runner.py:91} INFO - Job 232: Subtask err_report
[2024-07-24T15:02:13.771+0900] {task_command.py:426} INFO - Running <TaskInstance: import_db.err_report scheduled__2024-07-23T00:00:00+00:00 [running]> on host jeongui-MacBookPro.local
[2024-07-24T15:02:13.793+0900] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='import_db' AIRFLOW_CTX_TASK_ID='err_report' AIRFLOW_CTX_EXECUTION_DATE='2024-07-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-23T00:00:00+00:00'
[2024-07-24T15:02:13.794+0900] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T15:02:13.800+0900] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T
[2024-07-24T15:02:13.800+0900] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            echo "err report"\n           ']
[2024-07-24T15:02:13.803+0900] {subprocess.py:86} INFO - Output:
[2024-07-24T15:02:13.805+0900] {subprocess.py:93} INFO - err report
[2024-07-24T15:02:13.805+0900] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-24T15:02:13.805+0900] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T15:02:13.811+0900] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=import_db, task_id=err_report, run_id=scheduled__2024-07-23T00:00:00+00:00, execution_date=20240723T000000, start_date=20240724T060213, end_date=20240724T060213
[2024-07-24T15:02:13.858+0900] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-24T15:02:13.867+0900] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T15:02:13.867+0900] {local_task_job_runner.py:222} INFO - ::endgroup::
