[2024-07-24T12:43:18.272+0900] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T12:43:18.279+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_bash.copy.log scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-24T12:43:18.281+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_bash.copy.log scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-24T12:43:18.281+0900] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-07-24T12:43:18.285+0900] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): copy.log> on 2024-07-11 00:00:00+00:00
[2024-07-24T12:43:18.288+0900] {standard_task_runner.py:64} INFO - Started process 88646 to run task
[2024-07-24T12:43:18.290+0900] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'simple_bash', 'copy.log', 'scheduled__2024-07-11T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/simple_bash.py', '--cfg-path', '/var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T/tmppavuol6y']
[2024-07-24T12:43:18.292+0900] {standard_task_runner.py:91} INFO - Job 9: Subtask copy.log
[2024-07-24T12:43:18.306+0900] {task_command.py:426} INFO - Running <TaskInstance: simple_bash.copy.log scheduled__2024-07-11T00:00:00+00:00 [running]> on host jeongui-MacBookPro.local
[2024-07-24T12:43:18.326+0900] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='simple_bash' AIRFLOW_CTX_TASK_ID='copy.log' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-11T00:00:00+00:00'
[2024-07-24T12:43:18.327+0900] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T12:43:18.333+0900] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T
[2024-07-24T12:43:18.333+0900] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            mkdir -p ~/data/20240711\n            cp ~/logs/history_20240711*.log ~/data/20240711/\n        ']
[2024-07-24T12:43:18.336+0900] {subprocess.py:86} INFO - Output:
[2024-07-24T12:43:18.340+0900] {subprocess.py:93} INFO - cp: /Users/DE32/logs/history_20240711*.log: No such file or directory
[2024-07-24T12:43:18.340+0900] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-24T12:43:18.340+0900] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T12:43:18.344+0900] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DE32/.pyenv/versions/3.11.9/envs/note/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-24T12:43:18.345+0900] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=simple_bash, task_id=copy.log, run_id=scheduled__2024-07-11T00:00:00+00:00, execution_date=20240711T000000, start_date=20240724T034318, end_date=20240724T034318
[2024-07-24T12:43:18.349+0900] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task copy.log (Bash command failed. The command returned a non-zero exit code 1.; 88646)
[2024-07-24T12:43:18.352+0900] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-24T12:43:18.359+0900] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T12:43:18.359+0900] {local_task_job_runner.py:222} INFO - ::endgroup::
