[2024-07-24T15:32:04.049+0900] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T15:32:04.057+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_db.make_done scheduled__2024-07-18T00:00:00+00:00 [queued]>
[2024-07-24T15:32:04.059+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_db.make_done scheduled__2024-07-18T00:00:00+00:00 [queued]>
[2024-07-24T15:32:04.059+0900] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-24T15:32:04.063+0900] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): make_done> on 2024-07-18 00:00:00+00:00
[2024-07-24T15:32:04.065+0900] {standard_task_runner.py:64} INFO - Started process 96772 to run task
[2024-07-24T15:32:04.067+0900] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'import_db', 'make_done', 'scheduled__2024-07-18T00:00:00+00:00', '--job-id', '367', '--raw', '--subdir', 'DAGS_FOLDER/import_db.py', '--cfg-path', '/var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T/tmpci93tvca']
[2024-07-24T15:32:04.069+0900] {standard_task_runner.py:91} INFO - Job 367: Subtask make_done
[2024-07-24T15:32:04.083+0900] {task_command.py:426} INFO - Running <TaskInstance: import_db.make_done scheduled__2024-07-18T00:00:00+00:00 [running]> on host jeongui-MacBookPro.local
[2024-07-24T15:32:04.103+0900] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='import_db' AIRFLOW_CTX_TASK_ID='make_done' AIRFLOW_CTX_EXECUTION_DATE='2024-07-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-18T00:00:00+00:00'
[2024-07-24T15:32:04.104+0900] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T15:32:04.110+0900] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/qv/0knwm5h50ml0skpppwpbks_r0000gp/T
[2024-07-24T15:32:04.110+0900] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n                figlet "DONE"\n                DONE_PATH=~/data/done/_import/20240718\n                mkdir -p $DONE_PATH\n                echo "IMPORT_DONE_PATH=$DONE_PATH"\n                touch $DONE_PATH/_DONE\n            ']
[2024-07-24T15:32:04.113+0900] {subprocess.py:86} INFO - Output:
[2024-07-24T15:32:04.115+0900] {subprocess.py:93} INFO - /bin/bash: line 1: figlet: command not found
[2024-07-24T15:32:04.116+0900] {subprocess.py:93} INFO - IMPORT_DONE_PATH=/Users/DE32/data/done/_import/20240718
[2024-07-24T15:32:04.117+0900] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-24T15:32:04.118+0900] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T15:32:04.123+0900] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=import_db, task_id=make_done, run_id=scheduled__2024-07-18T00:00:00+00:00, execution_date=20240718T000000, start_date=20240724T063204, end_date=20240724T063204
[2024-07-24T15:32:04.128+0900] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-24T15:32:04.133+0900] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T15:32:04.133+0900] {local_task_job_runner.py:222} INFO - ::endgroup::
